version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
    ports:
      - "3005:80"
    networks:
      - essay-platform-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - server/.env
    networks:
      - essay-platform-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./server/src/config/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./server/src/config/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - essay-platform-network

networks:
  essay-platform-network:
    driver: bridge

volumes:
  postgres_data:
